[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "builder"
version = "1.0.0"
description = "Build tools for Dockerifles"
readme = "README.md"

requires-python = ">=3.10"

dependencies = [
  "click>=8.1,<9",
  "Jinja2>=3.1,<4",
  "jsonschema>=4.23,<5",
  "PyYAML>=6,<7",
  "rich>=13.7,<15",
]

[project.scripts]
builder = "image_builder.cli:cli"

[tool.setuptools.packages.find]
where = ["src"]
