# syntax=docker/dockerfile:1
FROM {{ upstream.image }}:{{ upstream.tag }}@{{ upstream.digest }}
ARG BUILD_DATE
ARG REVISION
ARG VERSION
LABEL org.opencontainers.image.title="Organization Busybox Base" \
  org.opencontainers.image.description="{{ description }}" \
  org.opencontainers.image.version="${VERSION}" \
  org.opencontainers.image.created="${BUILD_DATE}" \
  org.opencontainers.image.revision="${REVISION}" \
  org.opencontainers.image.source="https://github.com/nickkostov/docker"
RUN addgroup -S -g {{ user.gid }} {{ user.name }} && adduser -S -D -H -u {{ user.uid }} -G {{ user.name }} -s {{ user.shell }} {{ user.name }}
WORKDIR {{ user.workdir }}
USER {{ user.uid }}:{{ user.gid }}
