FROM {{ upstream.image }}:{{ upstream.tag }}@{{ upstream.digest }}
ARG BUILD_DATE
ARG REVISION
ARG VERSION
LABEL org.opencontainers.image.title="Organization Ubuntu Base" \
  org.opencontainers.image.description="{{ description }}" \
  org.opencontainers.image.version="${VERSION}" \
  org.opencontainers.image.created="${BUILD_DATE}" \
  org.opencontainers.image.revision="${REVISION}" \
  org.opencontainers.image.source="https://github.com/nickkostov/docker"
RUN groupadd --gid {{ user.gid }} {{ user.name }} \
  && useradd --uid {{ user.uid }} --gid {{ user.gid }} --no-create-home --home-dir {{ user.workdir }} --shell {{ user.shell }} {{ user.name }} \
  && mkdir -p {{ user.workdir }} \
  && chown {{ user.uid }}:{{ user.gid }} {{ user.workdir }}
WORKDIR {{ user.workdir }}
USER {{ user.uid }}:{{ user.gid }}
