name: Test ARC runners

on:
  workflow_dispatch:

jobs:
  ubuntu-2404:
    runs-on: metal-ubuntu-2404
    steps:
      - name: Check runner
        run: |
          echo "Runner: $RUNNER_NAME"
          echo "OS:"
          cat /etc/os-release
          echo "Kernel:"
          uname -a

  ubuntu-2604:
    runs-on: metal-ubuntu-2604
    steps:
      - name: Check runner
        run: |
          echo "Runner: $RUNNER_NAME"
          echo "OS:"
          cat /etc/os-release
          echo "Kernel:"
          uname -a
          